#################################################################
# Analysis of FBP and TBE in the context of:
# 1) 1000 trees infered from 1000 bootstrap alignments: 
#    Replicates are generated by sampling with replacement the
#    initial simulated alignment.
# 2) 1000 trees infered from 1000 simulated alignments: 
#    Replicates are generated from the true model.
########################################################

nextflow run trees_raxml.nf -c nextflow_configs/trees_raxml.config \
    --datadir '../mammals_COI5P/results/fasttree/trees'            \
    --resultdir 'results_raxml_no_noise/indelible'                 \
    --raterogue 0.0                                                \
    --rateshuffle 0.0                                              \
    --nboot 1000                                                   \
    -w work_raxml_no_noise

nextflow run trees_raxml.nf -c nextflow_configs/trees_raxml.config \
    --datadir '../mammals_COI5P/results/fasttree/trees'            \
    --resultdir 'results_raxml_noise/indelible'                    \
    --raterogue 0.05                                               \
    --rateshuffle 0.5                                              \
    --nboot 1000                                                   \
    -w work_raxml_noise                                            \
    -resume

nextflow run trees_fasttree.nf -c nextflow_configs/trees_fasttree.config \
    --datadir ../mammals_COI5P/results/fasttree/trees                    \
    --resultdir results_fasttree_noise/indelible                         \
    --raterogue 0.05                                                     \
    --rateshuffle 0.5                                                    \
    --nboot 1000                                                         \
    -w work_fasttree_noise                                               \
    -resume

nextflow run trees_fasttree.nf -c nextflow_configs/trees_fasttree.config \
    --datadir '../mammals_COI5P/results/fasttree/trees'                  \
    --resultdir 'results_fasttree_no_noise/indelible'                    \
    --raterogue 0.0                                                      \
    --rateshuffle 0.0                                                    \
    --nboot 1000                                                         \
    -w work_fasttree_no_noise
